version: "3.9"
services:
  site:
    image: dart-dev:stable
    build:
      context: .
      target: dev
    command: ["make", "serve"]
    env_file: .env
    environment:
      - NODE_ENV=development
    ports:
      - "4000:4000"
      - "5500:5500"
      - "8080:8080"
    volumes:
      - ./.eleventy.js:/app/.eleventy.js
      - ./.eleventyignore:/app/.eleventyignore
      - ./_site:/app/_site
      - ./.firebaserc:/app/.firebaserc
      - ./analysis_options.yaml:/app/analysis_options.yaml
      - ./build.excerpt.yaml:/app/build.excerpt.yaml
      - ./examples:/app/examples
      - ./firebase.json:/app/firebase.json
      - ./Makefile:/app/Makefile
      - ./package-lock.json:/app/package-lock.json
      - ./package.json:/app/package.json
      - ./pubspec.yaml:/app/pubspec.yaml
      - ./site-shared:/app/site-shared
      - ./src:/app/src
      - ./tool:/app/tool
